### ISSUE TITLE
Upload artifacts to maven central

### ISSUE THREAD

**Issue by jnehring** [freme-project/FREMECommon#39]
Currently all our maven artifacts reside on a nexus installation on the freme-dev server. We will upload it to Maven central so the artifacts can live after the projects lifetime.

This is the guide how this works: https://maven.apache.org/guides/mini/guide-central-repository-upload.html

**Comment by jnehring** [comment]
* make a new branch of fremecommon
* change version number to 0.1 in pom.xml
* apply changes in the guide
* use mvn:deploy to upload the artifact to maven central

**Comment by jnehring** [comment]
When you have uploaded an artifact to maven central, please write a guide on how to upload an artifact. Currently I do not know which information the guide will contain so please collect all important information and links on how to upload an artifact here in this issue.

**Comment by bgrusdt** [comment]
## Upload artifacts to the Central Repository
All FREME artifcats can be found in the 
[Central Repository](http://central.sonatype.org/?__hstc=239247836.b459aee40da923fa4a45645a31cddadf.1477582531140.1477582531140.1477605428269.2&__hssc=239247836.1.1477605428269&__hsfp=190473045&__utma=246996102.1998389910.1476968965.1477571303.1477605428.9&__utmb=246996102.2.10.1477605428&__utmc=246996102&__utmx=-&__utmz=246996102.1477468869.3.2.utmcsr=google|utmccn=(organic)|utmcmd=organic|utmctr=(not%20provided)&__utmv=-&__utmk=44786983) 
so everyone can access them easily.

This article shall help developpers to prepare their artifacts such that they can be uploaded to the repository. For 
detailed instructions, have a look at the [official documentation](http://central.sonatype.org/pages/producers.html).

## Getting access

First of all, you need to sign up to [Sonatype JIRA](https://issues.sonatype.org/secure/Signup!default.jspa) which 
automatically creates a JIRA issue for your request. You will be asked to enter the groupID for your artefacts and for 
some additional information such as the website of your project. The groupID of the FREME project is 
**com.github.freme-project**, i.e. in the [repository](https://repo1.maven.org/maven2/) you will find it under
**com/github/freme-project**. This groupID is used instead of **eu.freme** because we do not own the FREME-servers, i.e.
they will shutdown when the lifetime of the  project comes to an end. 

Before you can actually upload artifacts you will have to wait for Sonatype to review the information that you  provided 
This  can take up to two buisiness days but usually it only takes a couple of hours. They will comment on your Ticket 
that your configuration has been prepared.

## Preparing the data 

There are a few requirements that need to be fullfilled by your projects in order to successfully upload their artifacts.
A detailed description for the requirements can be found on the [Sonatype documentation](http://central.sonatype.org/pages/requirements.html).

* Provide Javadoc and Source archives. You can use the [Maven source-plugin](https://maven.apache.org/plugins/maven-source-plugin/usage.html). 
* Your files need to be signed with a GPG/PGP signature which has to be provided for each file by a **.asc** file 
containing the signature. After the configuration of the keys, as described in the [GPG article](http://maven.apache.org/plugins/maven-gpg-plugin/usage.html)
in the Sonatype documentation, this can be done with the [maven-gpg-plugin](http://maven.apache.org/plugins/maven-gpg-plugin/usage.html).
    - TODO check for scala-projects since it was mentioned that fake ones are needed
* The project's **pom** file must contain the following information
    * groupId - The one you specified when signing in. It specifies the namespace that you own and to which your
     artifacts are uploaded. You can add subfolders by appending **.yoursubfolder** to the groupId in your **pom** file.
    * artifactId
    * version
    * packaging (only if it's not the default, i.e. *jar*)
* Provide License information. The FREME-project uses the [Maven License Plugin](http://code.mycila.com/license-maven-plugin/). 
* Provide Developpers information 
    TODO check how must officially be mentioned.
    
```xml
<developers>  
  <developer>  
    <name>Jan Nehring</name>  
        <email>jan.nehring@dfki.de</email>  
        <organization>DFKI</organization>  
        <organizationUrl>http://www.dfki.de</organizationUrl>  
  </developer>  
</developers>
```
* Provide information about the Source Control System (SCM). The following example shows the information for the freme-parent project.
    
```xml
<scm>
    <connection>scm:git:git@github.com:freme-project/freme-parent.git</connection>
    <url>scm:git:git@github.com/freme-project:freme-parent.git</url>
    <developerConnection>scm:git:git@github.com:freme-project/freme-parent.git</developerConnection>
</scm>
```
* Do not use `` <repositories/></repositories> `` and `` <pluginRepositories></pluginRepositories> `` but publish **all** 
required components to the Central Repository


## Deployment

In order to deploy to the Central Repository, the correct configuration needs to be added to the project's **pom** file.

````xml
<distributionManagement>
    <snapshotRepository>
        <id>ossrh</id>
        <url>https://oss.sonatype.org/content/repositories/snapshots</url>
    </snapshotRepository>
    <repository>
        <id>ossrh</id>
        <url>https://oss.sonatype.org/service/local/staging/deploy/maven2/</url>
    </repository>
</distributionManagement>
````

The ```` <id> ```` must be identical to the ```` <id> ```` specified in your **settings.xml** file which is stored or 
needs to be created directly inside your maven folder, e.g. **~/.m2/**. The file should contain the following 
information:

````xml
<settings>
  <servers>
    <server>
      <id>ossrh</id>
      <username>your-jira-sonatype-username</username>
      <password>your-jira-sonatype-password</password>
    </server>
  </servers>
</settings>
````

You can upload SNAPSHOT-versions of your project, but they will not be synchronized with the Central Repository and your
projects do not necessarily have to fulfill the requirements mentioned above. In the Sonatype documentation you will
find a [detailed article](http://central.sonatype.org/pages/apache-maven.html) about the Deployment with Apache Maven.

When your maven build was successfull, you will find your project in the [Nexus Repository Manager](https://oss.sonatype.org/#stagingRepositories)
under **Staging Repositories**. Now you have to close the Repository with the close icon on top which will trigger 
automatic checks that verify if your project fulfills all requirements. If it does, you can release it by clicking on 
the release icon on top. Otherwise you will have to drop the project, fix the problems and do it again. When you 
finished this, you have to comment again on the JIRA Ticket created in the beginning that you promoted your first 
release. 
In order to see if your project is available now in the Central Repository, browse its contents on the
[Central Repository Website](https://search.maven.org/).


## Permissions for your namespace in the Central Repository

The owner of the namespace can add people to the list of developpers that are allowed to publish artifacts to your
namespace.
  --- TODO check how (field appeared when signing up)

  --- TODO check if and how owner can be changed.

**Comment by jnehring** [comment]
* Please try to change the group id to eu.freme. ...
* check for scala-projects since it was mentioned that fake ones are needed
* Jan created freme-developer user and put it in the FREME keystore. Please give this user read / write access to snapshots and releases, no admin rights for maven central.
* Please give all rights to freme-admin user.
* Try to add the PGP key (or keys) to the keystore. Maybe under "notes"?
* Try to upload freme-common. Please try if it is possible to remove distribution management and repositories tags because the first is inherited from freme-parent and the second is not needed.

Next steps - please do not do this right away.

* Update all pom.xml files with developer information, maybe more plugins (java doc, ...). Remove all repository tags and hopefully distribution management also
* Upload all artifacts to maven central
* All developers need to create a settings.xml

**Comment by jnehring** [comment]
> Please try to change the group id to eu.freme. ...

done

> check for scala-projects since it was mentioned that fake ones are needed

done but needs to be checked again. we will upload all artifacts and see if there is a problem with freme 
ner

> Jan created freme-developer user and put it in the FREME keystore. Please give this user read / write access to snapshots and releases, no admin rights for maven central.

done

> Please give all rights to freme-admin user.

pending

> Try to add the PGP key (or keys) to the keystore. Maybe under "notes"?

this needs to be tested with the freme-developer user before we can add the key to the keystore

> Try to upload freme-common. Please try if it is possible to remove distribution management and repositories tags because the first is inherited from freme-parent and the second is not needed.

removed the tags, uploaded it to the stating repo. this worked out, but it is not published on maven central.

Next steps

* move freme-common pom.xml to a branch. set the version number to 0.11 and the parent to the freme-parent artifact on maven central (http://search.maven.org/#search%7Cga%7C1%7Ca%3A%22freme-parent%22)
* publish fremecommon in version 0.11 on maven central
* delete local maven repository (rm -rf ~/.m2/repository/eu) and rebuild fremecommon. it should download freme-parent from maven central.
* When this works, please update all group ids.
* Update all developer tags. This waits for #42

**Comment by jnehring** [comment]
All steps above done.

Please check if there is a way to gpg sign the artifacts only during release so normal developers do not need to setup gpg.

**Comment by bgrusdt** [comment]
> Please check if there is a way to gpg sign the artifacts only during release so normal developers do not need to setup gpg.

I think this can be done with profiles in the pom file. I added what I think is necessary, there was some information about this in the [documentation](http://central.sonatype.org/pages/apache-maven.html#performing-a-release-deployment-with-the-maven-release-plugin)
I tried to do a release for freme-parent to see if it worked, but that did not work out, but I think because I did not do it correctly, @jnehring can you have a look at it please?

> Check if the artifacts are available in maven central.

They are not available yet. I'd try to release again with the new profile and the deploy goal and investigate more if this also fails.

> Create "Publish Maven artifacts" documentation article in "FREME for developers".

[This](http://127.0.0.1:4000/knowledge-base/freme-for-developers/publish-maven-artifacts.html) is the article. I still have to add a section about the release. I will do that when we have uploaded everything to the central repository.

> Prepare epublib poms

done. I changed the distributionManagement Tag to ossrh (snapshot) and maven-central (release) gpg profile added

> * add information about maven settings.xml and the freme-developer user to https://freme-project.github.io/knowledge-base/freme-for-developers/developers-getting-started.html

I just added the small [paragraph](https://api-dev.freme-project.eu/doc/knowledge-base/freme-for-developers/developers-getting-started.html) 'Configure .settings.xml'.. What about the private key passphrase we need for deploying to maven central? Did we put it into the settings.xml file? Then I'd add this to the paragraph as well. And what about the private key? Where do we want to document this?

> Check that FREME developer user has read access only

I think the freme-developer credentials inside the .settings.xml is just necessary for deploying to the snapshot repository, but it is not for accesing it. 
using this:
```
	<repositories>
		<repository>
			<id>ossrh</id>
			<url>https://oss.sonatype.org/content/repositories/snapshots/</url>
			<snapshots>
				<enabled>true</enabled>
			</snapshots>
		</repository>
	</repositories>
````
without specifying any ossrh user in the settings.xml works. I tried it out with a simple test project. I added this repositories tag to freme-parent, 
epublib and batch-processing-tool such that snapshots can be accessed.

**Comment by jnehring** [comment]
I released freme-parent, freme-common, basic services ,freme-ner and epublib and uploaded them to maven central: http://oss.sonatype.org/content/repositories/snapshots/eu/freme-project/

Currently we are waiting for https://github.com/freme-project/e-Link/issues/74 because this is the blocker to upload e-services and freme-packages to maven central.

> This is the article. I still have to add a section about the release. I will do that when we have uploaded everything to the central repository.

I think [this is the link](https://api-dev.freme-project.eu/doc/knowledge-base/freme-for-developers/publish-maven-artifacts.html). Please mention that most of these information are already added by freme-parent so there is no need to add javadoc or distribution management.

> I think the freme-developer credentials inside the .settings.xml is just necessary for deploying to the snapshot repository, but it is not for accesing it.

great

**Comment by jnehring** [comment]
This task is done
